# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWJjMTc5NDZiNGRhMWVhZDdmOGY0YzVkOWRhYTg2YjFlMjM4OTg2ZTBiZTQ5ZTg4Y2MzNDY2ZTc0ZDE0MjY5ODZlYWU5NGI1NTI1N2FiYTFjNDAyZTNhZWE5ZmQ0YWQxMjk4YTNlNmQ5YTlmNzFiNzM0YzVjNmMxZjJlMzk1ZWM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
